### ISSUE TITLE
NPE formatting a ValueSpecification

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.formatter#109]
I'm not sure exactly whose bug this is, but the symptom appears here.

```ceylon
    value node = ValueSpecification {
        name = LIdentifier("a");
        specifier = Specifier(StringLiteral("""a"""));
    };
    format(node.transform(RedHatTransformer(SimpleTokenFactory())));
```
results in:
```
Exception in thread "main" ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:975)
	at ceylon.formatter.FormattingVisitor.visitSpecifierStatement(FormattingVisitor.ceylon:1778)
	at com.redhat.ceylon.compiler.typechecker.tree.VisitorAdaptor.visit(VisitorAdaptor.java:229)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$SpecifierStatement.visit(Tree.java:3086)
	at ceylon.formatter.format_.format(format.ceylon:72)
	at ceylon.formatter.format_.format(format.ceylon:68)
```
Line 1778 of `FormattingVisitor.ceylon`:
```ceylon
writeSemicolon(fWriter, that.mainEndToken, context);
```

**Comment by lucaswerkmeister** [comment]
Hm, perhaps the `RedHatTransformer` isn’t generating a semicolon here. Let me check…

**Comment by lucaswerkmeister** [comment]
Yup, semicolon missing. IIRC we’re supposed to have tests for that, I need to check why they didn’t detect this…

**Comment by lucaswerkmeister** [comment]
Ah, `completeCompilationUnit` only contains `ValueSpecification` within named arguments (`SpecifiedArgument`), and `RedHatTransformer.transformSpecifiedArgument` handles that internally without using `transformValueSpecification`.

**Comment by lucaswerkmeister** [comment]
Should be fixed now.

**Comment by jvasileff** [comment]
Works great, thanks!
